title: Open Mentorship by Christian Naths
permalink: /:title/
# Build settings
sass:
    style: compressed
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
