title: Open Mentorship by Adam Whitcroft
permalink: /:title/
baseurl: http://adamwhitcroft.com/
# Build settings
sass:
    style: compressed
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
